version: 2

before:
  hooks:
    - go mod tidy

builds:
  - targets: [go_first_class]
    mod_timestamp: "{{ .CommitTimestamp }}"
    dir: ./cmd/genai
    env:
      - CGO_ENABLED=0
    flags:
      # trims path
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  name_template: "v{{ .Version }}"
