// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: genai/plugin/v1/provider.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Capability int32

const (
	Capability_CAPABILITY_UNSPECIFIED     Capability = 0
	Capability_CAPABILITY_CHAT_COMPLETION Capability = 1
	Capability_CAPABILITY_EMBEDDINGS      Capability = 2
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0: "CAPABILITY_UNSPECIFIED",
		1: "CAPABILITY_CHAT_COMPLETION",
		2: "CAPABILITY_EMBEDDINGS",
	}
	Capability_value = map[string]int32{
		"CAPABILITY_UNSPECIFIED":     0,
		"CAPABILITY_CHAT_COMPLETION": 1,
		"CAPABILITY_EMBEDDINGS":      2,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_genai_plugin_v1_provider_proto_enumTypes[0].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_genai_plugin_v1_provider_proto_enumTypes[0]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{0}
}

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_USER        Role = 1
	Role_ROLE_SYSTEM      Role = 2
	Role_ROLE_ASSISTANT   Role = 3
	Role_ROLE_TOOL        Role = 4
	Role_ROLE_TOOL_CALLS  Role = 5
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_USER",
		2: "ROLE_SYSTEM",
		3: "ROLE_ASSISTANT",
		4: "ROLE_TOOL",
		5: "ROLE_TOOL_CALLS",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_USER":        1,
		"ROLE_SYSTEM":      2,
		"ROLE_ASSISTANT":   3,
		"ROLE_TOOL":        4,
		"ROLE_TOOL_CALLS":  5,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_genai_plugin_v1_provider_proto_enumTypes[1].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_genai_plugin_v1_provider_proto_enumTypes[1]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{1}
}

type AttachmentType int32

const (
	AttachmentType_ATTACHMENT_TYPE_UNSPECIFIED AttachmentType = 0
	AttachmentType_ATTACHMENT_TYPE_IMAGE       AttachmentType = 1
	AttachmentType_ATTACHMENT_TYPE_AUDIO       AttachmentType = 2
	AttachmentType_ATTACHMENT_TYPE_VIDEO       AttachmentType = 3
	AttachmentType_ATTACHMENT_TYPE_DOCUMENT    AttachmentType = 4
)

// Enum value maps for AttachmentType.
var (
	AttachmentType_name = map[int32]string{
		0: "ATTACHMENT_TYPE_UNSPECIFIED",
		1: "ATTACHMENT_TYPE_IMAGE",
		2: "ATTACHMENT_TYPE_AUDIO",
		3: "ATTACHMENT_TYPE_VIDEO",
		4: "ATTACHMENT_TYPE_DOCUMENT",
	}
	AttachmentType_value = map[string]int32{
		"ATTACHMENT_TYPE_UNSPECIFIED": 0,
		"ATTACHMENT_TYPE_IMAGE":       1,
		"ATTACHMENT_TYPE_AUDIO":       2,
		"ATTACHMENT_TYPE_VIDEO":       3,
		"ATTACHMENT_TYPE_DOCUMENT":    4,
	}
)

func (x AttachmentType) Enum() *AttachmentType {
	p := new(AttachmentType)
	*p = x
	return p
}

func (x AttachmentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttachmentType) Descriptor() protoreflect.EnumDescriptor {
	return file_genai_plugin_v1_provider_proto_enumTypes[2].Descriptor()
}

func (AttachmentType) Type() protoreflect.EnumType {
	return &file_genai_plugin_v1_provider_proto_enumTypes[2]
}

func (x AttachmentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttachmentType.Descriptor instead.
func (AttachmentType) EnumDescriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{2}
}

type AttachmentSource int32

const (
	AttachmentSource_ATTACHMENT_SOURCE_UNSPECIFIED AttachmentSource = 0
	AttachmentSource_ATTACHMENT_SOURCE_BASE64      AttachmentSource = 1
	AttachmentSource_ATTACHMENT_SOURCE_URL         AttachmentSource = 2
)

// Enum value maps for AttachmentSource.
var (
	AttachmentSource_name = map[int32]string{
		0: "ATTACHMENT_SOURCE_UNSPECIFIED",
		1: "ATTACHMENT_SOURCE_BASE64",
		2: "ATTACHMENT_SOURCE_URL",
	}
	AttachmentSource_value = map[string]int32{
		"ATTACHMENT_SOURCE_UNSPECIFIED": 0,
		"ATTACHMENT_SOURCE_BASE64":      1,
		"ATTACHMENT_SOURCE_URL":         2,
	}
)

func (x AttachmentSource) Enum() *AttachmentSource {
	p := new(AttachmentSource)
	*p = x
	return p
}

func (x AttachmentSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttachmentSource) Descriptor() protoreflect.EnumDescriptor {
	return file_genai_plugin_v1_provider_proto_enumTypes[3].Descriptor()
}

func (AttachmentSource) Type() protoreflect.EnumType {
	return &file_genai_plugin_v1_provider_proto_enumTypes[3]
}

func (x AttachmentSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttachmentSource.Descriptor instead.
func (AttachmentSource) EnumDescriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{3}
}

type StreamChunkType int32

const (
	StreamChunkType_STREAM_CHUNK_TYPE_UNSPECIFIED StreamChunkType = 0
	StreamChunkType_STREAM_CHUNK_TYPE_DELTA       StreamChunkType = 1
	// Mirrors llm.StreamChunkTypeUsage, which no llm constructor produces: the
	// host rebuilds such a chunk as a delta carrying the usage.
	StreamChunkType_STREAM_CHUNK_TYPE_USAGE    StreamChunkType = 2
	StreamChunkType_STREAM_CHUNK_TYPE_ERROR    StreamChunkType = 3
	StreamChunkType_STREAM_CHUNK_TYPE_COMPLETE StreamChunkType = 4
)

// Enum value maps for StreamChunkType.
var (
	StreamChunkType_name = map[int32]string{
		0: "STREAM_CHUNK_TYPE_UNSPECIFIED",
		1: "STREAM_CHUNK_TYPE_DELTA",
		2: "STREAM_CHUNK_TYPE_USAGE",
		3: "STREAM_CHUNK_TYPE_ERROR",
		4: "STREAM_CHUNK_TYPE_COMPLETE",
	}
	StreamChunkType_value = map[string]int32{
		"STREAM_CHUNK_TYPE_UNSPECIFIED": 0,
		"STREAM_CHUNK_TYPE_DELTA":       1,
		"STREAM_CHUNK_TYPE_USAGE":       2,
		"STREAM_CHUNK_TYPE_ERROR":       3,
		"STREAM_CHUNK_TYPE_COMPLETE":    4,
	}
)

func (x StreamChunkType) Enum() *StreamChunkType {
	p := new(StreamChunkType)
	*p = x
	return p
}

func (x StreamChunkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamChunkType) Descriptor() protoreflect.EnumDescriptor {
	return file_genai_plugin_v1_provider_proto_enumTypes[4].Descriptor()
}

func (StreamChunkType) Type() protoreflect.EnumType {
	return &file_genai_plugin_v1_provider_proto_enumTypes[4]
}

func (x StreamChunkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamChunkType.Descriptor instead.
func (StreamChunkType) EnumDescriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{4}
}

type Error_Kind int32

const (
	Error_KIND_UNSPECIFIED Error_Kind = 0
	Error_KIND_HTTP        Error_Kind = 1
	Error_KIND_RATE_LIMIT  Error_Kind = 2
	Error_KIND_NO_MESSAGE  Error_Kind = 3
	Error_KIND_UNAVAILABLE Error_Kind = 4
	Error_KIND_VALIDATION  Error_Kind = 5
)

// Enum value maps for Error_Kind.
var (
	Error_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_HTTP",
		2: "KIND_RATE_LIMIT",
		3: "KIND_NO_MESSAGE",
		4: "KIND_UNAVAILABLE",
		5: "KIND_VALIDATION",
	}
	Error_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_HTTP":        1,
		"KIND_RATE_LIMIT":  2,
		"KIND_NO_MESSAGE":  3,
		"KIND_UNAVAILABLE": 4,
		"KIND_VALIDATION":  5,
	}
)

func (x Error_Kind) Enum() *Error_Kind {
	p := new(Error_Kind)
	*p = x
	return p
}

func (x Error_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_genai_plugin_v1_provider_proto_enumTypes[5].Descriptor()
}

func (Error_Kind) Type() protoreflect.EnumType {
	return &file_genai_plugin_v1_provider_proto_enumTypes[5]
}

func (x Error_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error_Kind.Descriptor instead.
func (Error_Kind) EnumDescriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{26, 0}
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{0}
}

type DescribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  []Capability           `protobuf:"varint,3,rep,packed,name=capabilities,proto3,enum=genai.plugin.v1.Capability" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DescribeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DescribeResponse) GetCapabilities() []Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ConfigureRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Capability Capability             `protobuf:"varint,1,opt,name=capability,proto3,enum=genai.plugin.v1.Capability" json:"capability,omitempty"`
	// Provider specific options, keyed without their environment prefix
	// (e.g. "MODEL_PATH" for GENAI_CHAT_COMPLETION_YZMA_MODEL_PATH).
	Options       map[string]string `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigureRequest) GetCapability() Capability {
	if x != nil {
		return x.Capability
	}
	return Capability_CAPABILITY_UNSPECIFIED
}

func (x *ConfigureRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigureResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{5}
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          AttachmentType         `protobuf:"varint,1,opt,name=type,proto3,enum=genai.plugin.v1.AttachmentType" json:"type,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Source        AttachmentSource       `protobuf:"varint,3,opt,name=source,proto3,enum=genai.plugin.v1.AttachmentSource" json:"source,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{6}
}

func (x *Attachment) GetType() AttachmentType {
	if x != nil {
		return x.Type
	}
	return AttachmentType_ATTACHMENT_TYPE_UNSPECIFIED
}

func (x *Attachment) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Attachment) GetSource() AttachmentSource {
	if x != nil {
		return x.Source
	}
	return AttachmentSource_ATTACHMENT_SOURCE_UNSPECIFIED
}

func (x *Attachment) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type CacheControl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Ttl           *string                `protobuf:"bytes,2,opt,name=ttl,proto3,oneof" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheControl) Reset() {
	*x = CacheControl{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheControl) ProtoMessage() {}

func (x *CacheControl) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheControl.ProtoReflect.Descriptor instead.
func (*CacheControl) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{7}
}

func (x *CacheControl) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CacheControl) GetTtl() string {
	if x != nil && x.Ttl != nil {
		return *x.Ttl
	}
	return ""
}

type ReasoningDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Data          string                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Format        string                 `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	Index         int32                  `protobuf:"varint,7,opt,name=index,proto3" json:"index,omitempty"`
	Signature     string                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasoningDetail) Reset() {
	*x = ReasoningDetail{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningDetail) ProtoMessage() {}

func (x *ReasoningDetail) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningDetail.ProtoReflect.Descriptor instead.
func (*ReasoningDetail) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{8}
}

func (x *ReasoningDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReasoningDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReasoningDetail) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ReasoningDetail) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ReasoningDetail) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ReasoningDetail) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ReasoningDetail) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ReasoningDetail) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type ToolCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// JSON encoded parameters.
	ParametersJson string `protobuf:"bytes,3,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{9}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetParametersJson() string {
	if x != nil {
		return x.ParametersJson
	}
	return ""
}

// Message is the wire form of every llm.Message implementation. The fields
// that are set decide which constructor the receiving side uses. Tool call
// and reasoning messages carry no attachments in llm, so none travel for
// them either.
type Message struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Role         Role                   `protobuf:"varint,1,opt,name=role,proto3,enum=genai.plugin.v1.Role" json:"role,omitempty"`
	Content      string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Attachments  []*Attachment          `protobuf:"bytes,3,rep,name=attachments,proto3" json:"attachments,omitempty"`
	CacheControl *CacheControl          `protobuf:"bytes,4,opt,name=cache_control,json=cacheControl,proto3" json:"cache_control,omitempty"`
	// Set on tool result messages (llm.ToolMessage).
	ToolCallId string `protobuf:"bytes,5,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	// Set on tool call messages (llm.ToolCallsMessage).
	ToolCalls []*ToolCall `protobuf:"bytes,6,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	// Set on reasoning messages (llm.ReasoningMessage).
	Reasoning        string             `protobuf:"bytes,7,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	ReasoningDetails []*ReasoningDetail `protobuf:"bytes,8,rep,name=reasoning_details,json=reasoningDetails,proto3" json:"reasoning_details,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{10}
}

func (x *Message) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *Message) GetCacheControl() *CacheControl {
	if x != nil {
		return x.CacheControl
	}
	return nil
}

func (x *Message) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *Message) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *Message) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *Message) GetReasoningDetails() []*ReasoningDetail {
	if x != nil {
		return x.ReasoningDetails
	}
	return nil
}

// Tool is a descriptor only: execution stays on the host side.
type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    *structpb.Struct       `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{11}
}

func (x *Tool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tool) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ResponseSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Schema        *structpb.Value        `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	Strict        bool                   `protobuf:"varint,4,opt,name=strict,proto3" json:"strict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseSchema) Reset() {
	*x = ResponseSchema{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseSchema) ProtoMessage() {}

func (x *ResponseSchema) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseSchema.ProtoReflect.Descriptor instead.
func (*ResponseSchema) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{12}
}

func (x *ResponseSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResponseSchema) GetSchema() *structpb.Value {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *ResponseSchema) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

type ReasoningOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Effort        *string                `protobuf:"bytes,1,opt,name=effort,proto3,oneof" json:"effort,omitempty"`
	MaxTokens     *int64                 `protobuf:"varint,2,opt,name=max_tokens,json=maxTokens,proto3,oneof" json:"max_tokens,omitempty"`
	Exclude       bool                   `protobuf:"varint,3,opt,name=exclude,proto3" json:"exclude,omitempty"`
	Enabled       *bool                  `protobuf:"varint,4,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasoningOptions) Reset() {
	*x = ReasoningOptions{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningOptions) ProtoMessage() {}

func (x *ReasoningOptions) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningOptions.ProtoReflect.Descriptor instead.
func (*ReasoningOptions) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{13}
}

func (x *ReasoningOptions) GetEffort() string {
	if x != nil && x.Effort != nil {
		return *x.Effort
	}
	return ""
}

func (x *ReasoningOptions) GetMaxTokens() int64 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

func (x *ReasoningOptions) GetExclude() bool {
	if x != nil {
		return x.Exclude
	}
	return false
}

func (x *ReasoningOptions) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type AudioOutputConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voice         string                 `protobuf:"bytes,1,opt,name=voice,proto3" json:"voice,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioOutputConfig) Reset() {
	*x = AudioOutputConfig{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioOutputConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioOutputConfig) ProtoMessage() {}

func (x *AudioOutputConfig) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioOutputConfig.ProtoReflect.Descriptor instead.
func (*AudioOutputConfig) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{14}
}

func (x *AudioOutputConfig) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *AudioOutputConfig) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type ChatCompletionOptions struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Messages            []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Tools               []*Tool                `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
	ToolChoice          string                 `protobuf:"bytes,3,opt,name=tool_choice,json=toolChoice,proto3" json:"tool_choice,omitempty"`
	Temperature         *float64               `protobuf:"fixed64,4,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	ResponseFormat      string                 `protobuf:"bytes,5,opt,name=response_format,json=responseFormat,proto3" json:"response_format,omitempty"`
	ResponseSchema      *ResponseSchema        `protobuf:"bytes,6,opt,name=response_schema,json=responseSchema,proto3" json:"response_schema,omitempty"`
	Seed                *int64                 `protobuf:"varint,7,opt,name=seed,proto3,oneof" json:"seed,omitempty"`
	MaxCompletionTokens *int64                 `protobuf:"varint,8,opt,name=max_completion_tokens,json=maxCompletionTokens,proto3,oneof" json:"max_completion_tokens,omitempty"`
	Reasoning           *ReasoningOptions      `protobuf:"bytes,9,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	Modalities          []string               `protobuf:"bytes,10,rep,name=modalities,proto3" json:"modalities,omitempty"`
	Audio               *AudioOutputConfig     `protobuf:"bytes,11,opt,name=audio,proto3" json:"audio,omitempty"`
	SessionId           string                 `protobuf:"bytes,12,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExtraFields         *structpb.Struct       `protobuf:"bytes,13,opt,name=extra_fields,json=extraFields,proto3" json:"extra_fields,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChatCompletionOptions) Reset() {
	*x = ChatCompletionOptions{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionOptions) ProtoMessage() {}

func (x *ChatCompletionOptions) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionOptions.ProtoReflect.Descriptor instead.
func (*ChatCompletionOptions) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{15}
}

func (x *ChatCompletionOptions) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatCompletionOptions) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ChatCompletionOptions) GetToolChoice() string {
	if x != nil {
		return x.ToolChoice
	}
	return ""
}

func (x *ChatCompletionOptions) GetTemperature() float64 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *ChatCompletionOptions) GetResponseFormat() string {
	if x != nil {
		return x.ResponseFormat
	}
	return ""
}

func (x *ChatCompletionOptions) GetResponseSchema() *ResponseSchema {
	if x != nil {
		return x.ResponseSchema
	}
	return nil
}

func (x *ChatCompletionOptions) GetSeed() int64 {
	if x != nil && x.Seed != nil {
		return *x.Seed
	}
	return 0
}

func (x *ChatCompletionOptions) GetMaxCompletionTokens() int64 {
	if x != nil && x.MaxCompletionTokens != nil {
		return *x.MaxCompletionTokens
	}
	return 0
}

func (x *ChatCompletionOptions) GetReasoning() *ReasoningOptions {
	if x != nil {
		return x.Reasoning
	}
	return nil
}

func (x *ChatCompletionOptions) GetModalities() []string {
	if x != nil {
		return x.Modalities
	}
	return nil
}

func (x *ChatCompletionOptions) GetAudio() *AudioOutputConfig {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *ChatCompletionOptions) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatCompletionOptions) GetExtraFields() *structpb.Struct {
	if x != nil {
		return x.ExtraFields
	}
	return nil
}

type ChatCompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Options       *ChatCompletionOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionRequest) Reset() {
	*x = ChatCompletionRequest{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionRequest) ProtoMessage() {}

func (x *ChatCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionRequest.ProtoReflect.Descriptor instead.
func (*ChatCompletionRequest) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{16}
}

func (x *ChatCompletionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ChatCompletionRequest) GetOptions() *ChatCompletionOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type Usage struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens        int64                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens    int64                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens         int64                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	CachedTokens        int64                  `protobuf:"varint,4,opt,name=cached_tokens,json=cachedTokens,proto3" json:"cached_tokens,omitempty"`
	CacheCreationTokens int64                  `protobuf:"varint,5,opt,name=cache_creation_tokens,json=cacheCreationTokens,proto3" json:"cache_creation_tokens,omitempty"`
	Cost                *float64               `protobuf:"fixed64,6,opt,name=cost,proto3,oneof" json:"cost,omitempty"`
	CostCurrency        string                 `protobuf:"bytes,7,opt,name=cost_currency,json=costCurrency,proto3" json:"cost_currency,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{17}
}

func (x *Usage) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *Usage) GetCachedTokens() int64 {
	if x != nil {
		return x.CachedTokens
	}
	return 0
}

func (x *Usage) GetCacheCreationTokens() int64 {
	if x != nil {
		return x.CacheCreationTokens
	}
	return 0
}

func (x *Usage) GetCost() float64 {
	if x != nil && x.Cost != nil {
		return *x.Cost
	}
	return 0
}

func (x *Usage) GetCostCurrency() string {
	if x != nil {
		return x.CostCurrency
	}
	return ""
}

type ChatCompletionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Message          *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ToolCalls        []*ToolCall            `protobuf:"bytes,2,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	Usage            *Usage                 `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	Reasoning        string                 `protobuf:"bytes,4,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	ReasoningDetails []*ReasoningDetail     `protobuf:"bytes,5,rep,name=reasoning_details,json=reasoningDetails,proto3" json:"reasoning_details,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatCompletionResponse) Reset() {
	*x = ChatCompletionResponse{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionResponse) ProtoMessage() {}

func (x *ChatCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionResponse.ProtoReflect.Descriptor instead.
func (*ChatCompletionResponse) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{18}
}

func (x *ChatCompletionResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ChatCompletionResponse) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *ChatCompletionResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ChatCompletionResponse) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *ChatCompletionResponse) GetReasoningDetails() []*ReasoningDetail {
	if x != nil {
		return x.ReasoningDetails
	}
	return nil
}

type ToolCallDelta struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Index           int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Id              string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ParametersDelta string                 `protobuf:"bytes,4,opt,name=parameters_delta,json=parametersDelta,proto3" json:"parameters_delta,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToolCallDelta) Reset() {
	*x = ToolCallDelta{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallDelta) ProtoMessage() {}

func (x *ToolCallDelta) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallDelta.ProtoReflect.Descriptor instead.
func (*ToolCallDelta) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{19}
}

func (x *ToolCallDelta) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ToolCallDelta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCallDelta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCallDelta) GetParametersDelta() string {
	if x != nil {
		return x.ParametersDelta
	}
	return ""
}

type StreamDelta struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Role             Role                   `protobuf:"varint,1,opt,name=role,proto3,enum=genai.plugin.v1.Role" json:"role,omitempty"`
	Content          string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ToolCalls        []*ToolCallDelta       `protobuf:"bytes,3,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	Reasoning        string                 `protobuf:"bytes,4,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	ReasoningDetails []*ReasoningDetail     `protobuf:"bytes,5,rep,name=reasoning_details,json=reasoningDetails,proto3" json:"reasoning_details,omitempty"`
	AudioData        string                 `protobuf:"bytes,6,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	Transcript       string                 `protobuf:"bytes,7,opt,name=transcript,proto3" json:"transcript,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamDelta) Reset() {
	*x = StreamDelta{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDelta) ProtoMessage() {}

func (x *StreamDelta) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDelta.ProtoReflect.Descriptor instead.
func (*StreamDelta) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{20}
}

func (x *StreamDelta) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *StreamDelta) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StreamDelta) GetToolCalls() []*ToolCallDelta {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *StreamDelta) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *StreamDelta) GetReasoningDetails() []*ReasoningDetail {
	if x != nil {
		return x.ReasoningDetails
	}
	return nil
}

func (x *StreamDelta) GetAudioData() string {
	if x != nil {
		return x.AudioData
	}
	return ""
}

func (x *StreamDelta) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

type StreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          StreamChunkType        `protobuf:"varint,1,opt,name=type,proto3,enum=genai.plugin.v1.StreamChunkType" json:"type,omitempty"`
	Delta         *StreamDelta           `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	Error         *Error                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChunk) Reset() {
	*x = StreamChunk{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunk) ProtoMessage() {}

func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunk.ProtoReflect.Descriptor instead.
func (*StreamChunk) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{21}
}

func (x *StreamChunk) GetType() StreamChunkType {
	if x != nil {
		return x.Type
	}
	return StreamChunkType_STREAM_CHUNK_TYPE_UNSPECIFIED
}

func (x *StreamChunk) GetDelta() *StreamDelta {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *StreamChunk) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *StreamChunk) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type EmbeddingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Inputs        []string               `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Dimensions    *int64                 `protobuf:"varint,3,opt,name=dimensions,proto3,oneof" json:"dimensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingsRequest) Reset() {
	*x = EmbeddingsRequest{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingsRequest) ProtoMessage() {}

func (x *EmbeddingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingsRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingsRequest) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{22}
}

func (x *EmbeddingsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *EmbeddingsRequest) GetInputs() []string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *EmbeddingsRequest) GetDimensions() int64 {
	if x != nil && x.Dimensions != nil {
		return *x.Dimensions
	}
	return 0
}

type Embedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{23}
}

func (x *Embedding) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type EmbeddingsUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens  int64                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	TotalTokens   int64                  `protobuf:"varint,2,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingsUsage) Reset() {
	*x = EmbeddingsUsage{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingsUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingsUsage) ProtoMessage() {}

func (x *EmbeddingsUsage) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingsUsage.ProtoReflect.Descriptor instead.
func (*EmbeddingsUsage) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{24}
}

func (x *EmbeddingsUsage) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *EmbeddingsUsage) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type EmbeddingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*Embedding           `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	Usage         *EmbeddingsUsage       `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingsResponse) Reset() {
	*x = EmbeddingsResponse{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingsResponse) ProtoMessage() {}

func (x *EmbeddingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingsResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingsResponse) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{25}
}

func (x *EmbeddingsResponse) GetEmbeddings() []*Embedding {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

func (x *EmbeddingsResponse) GetUsage() *EmbeddingsUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

// Error carries the parts of an llm error that the host needs to rebuild a
// typed error, so that llm.IsRetryable and errors.Is/As keep working across
// the process boundary.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Kind          Error_Kind             `protobuf:"varint,2,opt,name=kind,proto3,enum=genai.plugin.v1.Error_Kind" json:"kind,omitempty"`
	StatusCode    int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Field         string                 `protobuf:"bytes,5,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_genai_plugin_v1_provider_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_genai_plugin_v1_provider_proto_rawDescGZIP(), []int{26}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetKind() Error_Kind {
	if x != nil {
		return x.Kind
	}
	return Error_KIND_UNSPECIFIED
}

func (x *Error) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Error) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Error) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

var File_genai_plugin_v1_provider_proto protoreflect.FileDescriptor

const file_genai_plugin_v1_provider_proto_rawDesc = "" +
	"\n" +
	"\x1egenai/plugin/v1/provider.proto\x12\x0fgenai.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x11\n" +
	"\x0fDescribeRequest\"\x81\x01\n" +
	"\x10DescribeResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12?\n" +
	"\fcapabilities\x18\x03 \x03(\x0e2\x1b.genai.plugin.v1.CapabilityR\fcapabilities\"\xd5\x01\n" +
	"\x10ConfigureRequest\x12;\n" +
	"\n" +
	"capability\x18\x01 \x01(\x0e2\x1b.genai.plugin.v1.CapabilityR\n" +
	"capability\x12H\n" +
	"\aoptions\x18\x02 \x03(\v2..genai.plugin.v1.ConfigureRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x11ConfigureResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"-\n" +
	"\x0eReleaseRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\x11\n" +
	"\x0fReleaseResponse\"\xad\x01\n" +
	"\n" +
	"Attachment\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.genai.plugin.v1.AttachmentTypeR\x04type\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x129\n" +
	"\x06source\x18\x03 \x01(\x0e2!.genai.plugin.v1.AttachmentSourceR\x06source\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\"A\n" +
	"\fCacheControl\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x15\n" +
	"\x03ttl\x18\x02 \x01(\tH\x00R\x03ttl\x88\x01\x01B\x06\n" +
	"\x04_ttl\"\xc3\x01\n" +
	"\x0fReasoningDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\x12\x14\n" +
	"\x05index\x18\a \x01(\x05R\x05index\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature\"W\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fparameters_json\x18\x03 \x01(\tR\x0eparametersJson\"\x9a\x03\n" +
	"\aMessage\x12)\n" +
	"\x04role\x18\x01 \x01(\x0e2\x15.genai.plugin.v1.RoleR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12=\n" +
	"\vattachments\x18\x03 \x03(\v2\x1b.genai.plugin.v1.AttachmentR\vattachments\x12B\n" +
	"\rcache_control\x18\x04 \x01(\v2\x1d.genai.plugin.v1.CacheControlR\fcacheControl\x12 \n" +
	"\ftool_call_id\x18\x05 \x01(\tR\n" +
	"toolCallId\x128\n" +
	"\n" +
	"tool_calls\x18\x06 \x03(\v2\x19.genai.plugin.v1.ToolCallR\ttoolCalls\x12\x1c\n" +
	"\treasoning\x18\a \x01(\tR\treasoning\x12M\n" +
	"\x11reasoning_details\x18\b \x03(\v2 .genai.plugin.v1.ReasoningDetailR\x10reasoningDetails\"u\n" +
	"\x04Tool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x127\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\"\x8e\x01\n" +
	"\x0eResponseSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12.\n" +
	"\x06schema\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x06schema\x12\x16\n" +
	"\x06strict\x18\x04 \x01(\bR\x06strict\"\xb2\x01\n" +
	"\x10ReasoningOptions\x12\x1b\n" +
	"\x06effort\x18\x01 \x01(\tH\x00R\x06effort\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_tokens\x18\x02 \x01(\x03H\x01R\tmaxTokens\x88\x01\x01\x12\x18\n" +
	"\aexclude\x18\x03 \x01(\bR\aexclude\x12\x1d\n" +
	"\aenabled\x18\x04 \x01(\bH\x02R\aenabled\x88\x01\x01B\t\n" +
	"\a_effortB\r\n" +
	"\v_max_tokensB\n" +
	"\n" +
	"\b_enabled\"A\n" +
	"\x11AudioOutputConfig\x12\x14\n" +
	"\x05voice\x18\x01 \x01(\tR\x05voice\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"\xb0\x05\n" +
	"\x15ChatCompletionOptions\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.genai.plugin.v1.MessageR\bmessages\x12+\n" +
	"\x05tools\x18\x02 \x03(\v2\x15.genai.plugin.v1.ToolR\x05tools\x12\x1f\n" +
	"\vtool_choice\x18\x03 \x01(\tR\n" +
	"toolChoice\x12%\n" +
	"\vtemperature\x18\x04 \x01(\x01H\x00R\vtemperature\x88\x01\x01\x12'\n" +
	"\x0fresponse_format\x18\x05 \x01(\tR\x0eresponseFormat\x12H\n" +
	"\x0fresponse_schema\x18\x06 \x01(\v2\x1f.genai.plugin.v1.ResponseSchemaR\x0eresponseSchema\x12\x17\n" +
	"\x04seed\x18\a \x01(\x03H\x01R\x04seed\x88\x01\x01\x127\n" +
	"\x15max_completion_tokens\x18\b \x01(\x03H\x02R\x13maxCompletionTokens\x88\x01\x01\x12?\n" +
	"\treasoning\x18\t \x01(\v2!.genai.plugin.v1.ReasoningOptionsR\treasoning\x12\x1e\n" +
	"\n" +
	"modalities\x18\n" +
	" \x03(\tR\n" +
	"modalities\x128\n" +
	"\x05audio\x18\v \x01(\v2\".genai.plugin.v1.AudioOutputConfigR\x05audio\x12\x1d\n" +
	"\n" +
	"session_id\x18\f \x01(\tR\tsessionId\x12:\n" +
	"\fextra_fields\x18\r \x01(\v2\x17.google.protobuf.StructR\vextraFieldsB\x0e\n" +
	"\f_temperatureB\a\n" +
	"\x05_seedB\x18\n" +
	"\x16_max_completion_tokens\"v\n" +
	"\x15ChatCompletionRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12@\n" +
	"\aoptions\x18\x02 \x01(\v2&.genai.plugin.v1.ChatCompletionOptionsR\aoptions\"\x9c\x02\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x03R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x03R\vtotalTokens\x12#\n" +
	"\rcached_tokens\x18\x04 \x01(\x03R\fcachedTokens\x122\n" +
	"\x15cache_creation_tokens\x18\x05 \x01(\x03R\x13cacheCreationTokens\x12\x17\n" +
	"\x04cost\x18\x06 \x01(\x01H\x00R\x04cost\x88\x01\x01\x12#\n" +
	"\rcost_currency\x18\a \x01(\tR\fcostCurrencyB\a\n" +
	"\x05_cost\"\xa1\x02\n" +
	"\x16ChatCompletionResponse\x122\n" +
	"\amessage\x18\x01 \x01(\v2\x18.genai.plugin.v1.MessageR\amessage\x128\n" +
	"\n" +
	"tool_calls\x18\x02 \x03(\v2\x19.genai.plugin.v1.ToolCallR\ttoolCalls\x12,\n" +
	"\x05usage\x18\x03 \x01(\v2\x16.genai.plugin.v1.UsageR\x05usage\x12\x1c\n" +
	"\treasoning\x18\x04 \x01(\tR\treasoning\x12M\n" +
	"\x11reasoning_details\x18\x05 \x03(\v2 .genai.plugin.v1.ReasoningDetailR\x10reasoningDetails\"t\n" +
	"\rToolCallDelta\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12)\n" +
	"\x10parameters_delta\x18\x04 \x01(\tR\x0fparametersDelta\"\xbd\x02\n" +
	"\vStreamDelta\x12)\n" +
	"\x04role\x18\x01 \x01(\x0e2\x15.genai.plugin.v1.RoleR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12=\n" +
	"\n" +
	"tool_calls\x18\x03 \x03(\v2\x1e.genai.plugin.v1.ToolCallDeltaR\ttoolCalls\x12\x1c\n" +
	"\treasoning\x18\x04 \x01(\tR\treasoning\x12M\n" +
	"\x11reasoning_details\x18\x05 \x03(\v2 .genai.plugin.v1.ReasoningDetailR\x10reasoningDetails\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x06 \x01(\tR\taudioData\x12\x1e\n" +
	"\n" +
	"transcript\x18\a \x01(\tR\n" +
	"transcript\"\xd3\x01\n" +
	"\vStreamChunk\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .genai.plugin.v1.StreamChunkTypeR\x04type\x122\n" +
	"\x05delta\x18\x02 \x01(\v2\x1c.genai.plugin.v1.StreamDeltaR\x05delta\x12,\n" +
	"\x05usage\x18\x03 \x01(\v2\x16.genai.plugin.v1.UsageR\x05usage\x12,\n" +
	"\x05error\x18\x04 \x01(\v2\x16.genai.plugin.v1.ErrorR\x05error\"|\n" +
	"\x11EmbeddingsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x16\n" +
	"\x06inputs\x18\x02 \x03(\tR\x06inputs\x12#\n" +
	"\n" +
	"dimensions\x18\x03 \x01(\x03H\x00R\n" +
	"dimensions\x88\x01\x01B\r\n" +
	"\v_dimensions\"#\n" +
	"\tEmbedding\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\"Y\n" +
	"\x0fEmbeddingsUsage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x03R\fpromptTokens\x12!\n" +
	"\ftotal_tokens\x18\x02 \x01(\x03R\vtotalTokens\"\x88\x01\n" +
	"\x12EmbeddingsResponse\x12:\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\x1a.genai.plugin.v1.EmbeddingR\n" +
	"embeddings\x126\n" +
	"\x05usage\x18\x02 \x01(\v2 .genai.plugin.v1.EmbeddingsUsageR\x05usage\"\xa0\x02\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12/\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.genai.plugin.v1.Error.KindR\x04kind\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x14\n" +
	"\x05field\x18\x05 \x01(\tR\x05field\"\x80\x01\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tKIND_HTTP\x10\x01\x12\x13\n" +
	"\x0fKIND_RATE_LIMIT\x10\x02\x12\x13\n" +
	"\x0fKIND_NO_MESSAGE\x10\x03\x12\x14\n" +
	"\x10KIND_UNAVAILABLE\x10\x04\x12\x13\n" +
	"\x0fKIND_VALIDATION\x10\x05*c\n" +
	"\n" +
	"Capability\x12\x1a\n" +
	"\x16CAPABILITY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCAPABILITY_CHAT_COMPLETION\x10\x01\x12\x19\n" +
	"\x15CAPABILITY_EMBEDDINGS\x10\x02*t\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tROLE_USER\x10\x01\x12\x0f\n" +
	"\vROLE_SYSTEM\x10\x02\x12\x12\n" +
	"\x0eROLE_ASSISTANT\x10\x03\x12\r\n" +
	"\tROLE_TOOL\x10\x04\x12\x13\n" +
	"\x0fROLE_TOOL_CALLS\x10\x05*\xa0\x01\n" +
	"\x0eAttachmentType\x12\x1f\n" +
	"\x1bATTACHMENT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ATTACHMENT_TYPE_IMAGE\x10\x01\x12\x19\n" +
	"\x15ATTACHMENT_TYPE_AUDIO\x10\x02\x12\x19\n" +
	"\x15ATTACHMENT_TYPE_VIDEO\x10\x03\x12\x1c\n" +
	"\x18ATTACHMENT_TYPE_DOCUMENT\x10\x04*n\n" +
	"\x10AttachmentSource\x12!\n" +
	"\x1dATTACHMENT_SOURCE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ATTACHMENT_SOURCE_BASE64\x10\x01\x12\x19\n" +
	"\x15ATTACHMENT_SOURCE_URL\x10\x02*\xab\x01\n" +
	"\x0fStreamChunkType\x12!\n" +
	"\x1dSTREAM_CHUNK_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17STREAM_CHUNK_TYPE_DELTA\x10\x01\x12\x1b\n" +
	"\x17STREAM_CHUNK_TYPE_USAGE\x10\x02\x12\x1b\n" +
	"\x17STREAM_CHUNK_TYPE_ERROR\x10\x03\x12\x1e\n" +
	"\x1aSTREAM_CHUNK_TYPE_COMPLETE\x10\x042\xfd\x01\n" +
	"\bProvider\x12O\n" +
	"\bDescribe\x12 .genai.plugin.v1.DescribeRequest\x1a!.genai.plugin.v1.DescribeResponse\x12R\n" +
	"\tConfigure\x12!.genai.plugin.v1.ConfigureRequest\x1a\".genai.plugin.v1.ConfigureResponse\x12L\n" +
	"\aRelease\x12\x1f.genai.plugin.v1.ReleaseRequest\x1a .genai.plugin.v1.ReleaseResponse2\xd3\x01\n" +
	"\x0eChatCompletion\x12a\n" +
	"\x0eChatCompletion\x12&.genai.plugin.v1.ChatCompletionRequest\x1a'.genai.plugin.v1.ChatCompletionResponse\x12^\n" +
	"\x14ChatCompletionStream\x12&.genai.plugin.v1.ChatCompletionRequest\x1a\x1c.genai.plugin.v1.StreamChunk0\x012c\n" +
	"\n" +
	"Embeddings\x12U\n" +
	"\n" +
	"Embeddings\x12\".genai.plugin.v1.EmbeddingsRequest\x1a#.genai.plugin.v1.EmbeddingsResponseBNZLgithub.com/bornholm/genai/llm/provider/plugin/proto/genai/plugin/v1;pluginv1b\x06proto3"

var (
	file_genai_plugin_v1_provider_proto_rawDescOnce sync.Once
	file_genai_plugin_v1_provider_proto_rawDescData []byte
)

func file_genai_plugin_v1_provider_proto_rawDescGZIP() []byte {
	file_genai_plugin_v1_provider_proto_rawDescOnce.Do(func() {
		file_genai_plugin_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_genai_plugin_v1_provider_proto_rawDesc), len(file_genai_plugin_v1_provider_proto_rawDesc)))
	})
	return file_genai_plugin_v1_provider_proto_rawDescData
}

var file_genai_plugin_v1_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_genai_plugin_v1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_genai_plugin_v1_provider_proto_goTypes = []any{
	(Capability)(0),                // 0: genai.plugin.v1.Capability
	(Role)(0),                      // 1: genai.plugin.v1.Role
	(AttachmentType)(0),            // 2: genai.plugin.v1.AttachmentType
	(AttachmentSource)(0),          // 3: genai.plugin.v1.AttachmentSource
	(StreamChunkType)(0),           // 4: genai.plugin.v1.StreamChunkType
	(Error_Kind)(0),                // 5: genai.plugin.v1.Error.Kind
	(*DescribeRequest)(nil),        // 6: genai.plugin.v1.DescribeRequest
	(*DescribeResponse)(nil),       // 7: genai.plugin.v1.DescribeResponse
	(*ConfigureRequest)(nil),       // 8: genai.plugin.v1.ConfigureRequest
	(*ConfigureResponse)(nil),      // 9: genai.plugin.v1.ConfigureResponse
	(*ReleaseRequest)(nil),         // 10: genai.plugin.v1.ReleaseRequest
	(*ReleaseResponse)(nil),        // 11: genai.plugin.v1.ReleaseResponse
	(*Attachment)(nil),             // 12: genai.plugin.v1.Attachment
	(*CacheControl)(nil),           // 13: genai.plugin.v1.CacheControl
	(*ReasoningDetail)(nil),        // 14: genai.plugin.v1.ReasoningDetail
	(*ToolCall)(nil),               // 15: genai.plugin.v1.ToolCall
	(*Message)(nil),                // 16: genai.plugin.v1.Message
	(*Tool)(nil),                   // 17: genai.plugin.v1.Tool
	(*ResponseSchema)(nil),         // 18: genai.plugin.v1.ResponseSchema
	(*ReasoningOptions)(nil),       // 19: genai.plugin.v1.ReasoningOptions
	(*AudioOutputConfig)(nil),      // 20: genai.plugin.v1.AudioOutputConfig
	(*ChatCompletionOptions)(nil),  // 21: genai.plugin.v1.ChatCompletionOptions
	(*ChatCompletionRequest)(nil),  // 22: genai.plugin.v1.ChatCompletionRequest
	(*Usage)(nil),                  // 23: genai.plugin.v1.Usage
	(*ChatCompletionResponse)(nil), // 24: genai.plugin.v1.ChatCompletionResponse
	(*ToolCallDelta)(nil),          // 25: genai.plugin.v1.ToolCallDelta
	(*StreamDelta)(nil),            // 26: genai.plugin.v1.StreamDelta
	(*StreamChunk)(nil),            // 27: genai.plugin.v1.StreamChunk
	(*EmbeddingsRequest)(nil),      // 28: genai.plugin.v1.EmbeddingsRequest
	(*Embedding)(nil),              // 29: genai.plugin.v1.Embedding
	(*EmbeddingsUsage)(nil),        // 30: genai.plugin.v1.EmbeddingsUsage
	(*EmbeddingsResponse)(nil),     // 31: genai.plugin.v1.EmbeddingsResponse
	(*Error)(nil),                  // 32: genai.plugin.v1.Error
	nil,                            // 33: genai.plugin.v1.ConfigureRequest.OptionsEntry
	(*structpb.Struct)(nil),        // 34: google.protobuf.Struct
	(*structpb.Value)(nil),         // 35: google.protobuf.Value
}
var file_genai_plugin_v1_provider_proto_depIdxs = []int32{
	0,  // 0: genai.plugin.v1.DescribeResponse.capabilities:type_name -> genai.plugin.v1.Capability
	0,  // 1: genai.plugin.v1.ConfigureRequest.capability:type_name -> genai.plugin.v1.Capability
	33, // 2: genai.plugin.v1.ConfigureRequest.options:type_name -> genai.plugin.v1.ConfigureRequest.OptionsEntry
	2,  // 3: genai.plugin.v1.Attachment.type:type_name -> genai.plugin.v1.AttachmentType
	3,  // 4: genai.plugin.v1.Attachment.source:type_name -> genai.plugin.v1.AttachmentSource
	1,  // 5: genai.plugin.v1.Message.role:type_name -> genai.plugin.v1.Role
	12, // 6: genai.plugin.v1.Message.attachments:type_name -> genai.plugin.v1.Attachment
	13, // 7: genai.plugin.v1.Message.cache_control:type_name -> genai.plugin.v1.CacheControl
	15, // 8: genai.plugin.v1.Message.tool_calls:type_name -> genai.plugin.v1.ToolCall
	14, // 9: genai.plugin.v1.Message.reasoning_details:type_name -> genai.plugin.v1.ReasoningDetail
	34, // 10: genai.plugin.v1.Tool.parameters:type_name -> google.protobuf.Struct
	35, // 11: genai.plugin.v1.ResponseSchema.schema:type_name -> google.protobuf.Value
	16, // 12: genai.plugin.v1.ChatCompletionOptions.messages:type_name -> genai.plugin.v1.Message
	17, // 13: genai.plugin.v1.ChatCompletionOptions.tools:type_name -> genai.plugin.v1.Tool
	18, // 14: genai.plugin.v1.ChatCompletionOptions.response_schema:type_name -> genai.plugin.v1.ResponseSchema
	19, // 15: genai.plugin.v1.ChatCompletionOptions.reasoning:type_name -> genai.plugin.v1.ReasoningOptions
	20, // 16: genai.plugin.v1.ChatCompletionOptions.audio:type_name -> genai.plugin.v1.AudioOutputConfig
	34, // 17: genai.plugin.v1.ChatCompletionOptions.extra_fields:type_name -> google.protobuf.Struct
	21, // 18: genai.plugin.v1.ChatCompletionRequest.options:type_name -> genai.plugin.v1.ChatCompletionOptions
	16, // 19: genai.plugin.v1.ChatCompletionResponse.message:type_name -> genai.plugin.v1.Message
	15, // 20: genai.plugin.v1.ChatCompletionResponse.tool_calls:type_name -> genai.plugin.v1.ToolCall
	23, // 21: genai.plugin.v1.ChatCompletionResponse.usage:type_name -> genai.plugin.v1.Usage
	14, // 22: genai.plugin.v1.ChatCompletionResponse.reasoning_details:type_name -> genai.plugin.v1.ReasoningDetail
	1,  // 23: genai.plugin.v1.StreamDelta.role:type_name -> genai.plugin.v1.Role
	25, // 24: genai.plugin.v1.StreamDelta.tool_calls:type_name -> genai.plugin.v1.ToolCallDelta
	14, // 25: genai.plugin.v1.StreamDelta.reasoning_details:type_name -> genai.plugin.v1.ReasoningDetail
	4,  // 26: genai.plugin.v1.StreamChunk.type:type_name -> genai.plugin.v1.StreamChunkType
	26, // 27: genai.plugin.v1.StreamChunk.delta:type_name -> genai.plugin.v1.StreamDelta
	23, // 28: genai.plugin.v1.StreamChunk.usage:type_name -> genai.plugin.v1.Usage
	32, // 29: genai.plugin.v1.StreamChunk.error:type_name -> genai.plugin.v1.Error
	29, // 30: genai.plugin.v1.EmbeddingsResponse.embeddings:type_name -> genai.plugin.v1.Embedding
	30, // 31: genai.plugin.v1.EmbeddingsResponse.usage:type_name -> genai.plugin.v1.EmbeddingsUsage
	5,  // 32: genai.plugin.v1.Error.kind:type_name -> genai.plugin.v1.Error.Kind
	6,  // 33: genai.plugin.v1.Provider.Describe:input_type -> genai.plugin.v1.DescribeRequest
	8,  // 34: genai.plugin.v1.Provider.Configure:input_type -> genai.plugin.v1.ConfigureRequest
	10, // 35: genai.plugin.v1.Provider.Release:input_type -> genai.plugin.v1.ReleaseRequest
	22, // 36: genai.plugin.v1.ChatCompletion.ChatCompletion:input_type -> genai.plugin.v1.ChatCompletionRequest
	22, // 37: genai.plugin.v1.ChatCompletion.ChatCompletionStream:input_type -> genai.plugin.v1.ChatCompletionRequest
	28, // 38: genai.plugin.v1.Embeddings.Embeddings:input_type -> genai.plugin.v1.EmbeddingsRequest
	7,  // 39: genai.plugin.v1.Provider.Describe:output_type -> genai.plugin.v1.DescribeResponse
	9,  // 40: genai.plugin.v1.Provider.Configure:output_type -> genai.plugin.v1.ConfigureResponse
	11, // 41: genai.plugin.v1.Provider.Release:output_type -> genai.plugin.v1.ReleaseResponse
	24, // 42: genai.plugin.v1.ChatCompletion.ChatCompletion:output_type -> genai.plugin.v1.ChatCompletionResponse
	27, // 43: genai.plugin.v1.ChatCompletion.ChatCompletionStream:output_type -> genai.plugin.v1.StreamChunk
	31, // 44: genai.plugin.v1.Embeddings.Embeddings:output_type -> genai.plugin.v1.EmbeddingsResponse
	39, // [39:45] is the sub-list for method output_type
	33, // [33:39] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_genai_plugin_v1_provider_proto_init() }
func file_genai_plugin_v1_provider_proto_init() {
	if File_genai_plugin_v1_provider_proto != nil {
		return
	}
	file_genai_plugin_v1_provider_proto_msgTypes[7].OneofWrappers = []any{}
	file_genai_plugin_v1_provider_proto_msgTypes[13].OneofWrappers = []any{}
	file_genai_plugin_v1_provider_proto_msgTypes[15].OneofWrappers = []any{}
	file_genai_plugin_v1_provider_proto_msgTypes[17].OneofWrappers = []any{}
	file_genai_plugin_v1_provider_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_genai_plugin_v1_provider_proto_rawDesc), len(file_genai_plugin_v1_provider_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_genai_plugin_v1_provider_proto_goTypes,
		DependencyIndexes: file_genai_plugin_v1_provider_proto_depIdxs,
		EnumInfos:         file_genai_plugin_v1_provider_proto_enumTypes,
		MessageInfos:      file_genai_plugin_v1_provider_proto_msgTypes,
	}.Build()
	File_genai_plugin_v1_provider_proto = out.File
	file_genai_plugin_v1_provider_proto_goTypes = nil
	file_genai_plugin_v1_provider_proto_depIdxs = nil
}
