// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: genai/plugin/v1/provider.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Provider_Describe_FullMethodName  = "/genai.plugin.v1.Provider/Describe"
	Provider_Configure_FullMethodName = "/genai.plugin.v1.Provider/Configure"
	Provider_Release_FullMethodName   = "/genai.plugin.v1.Provider/Release"
)

// ProviderClient is the client API for Provider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Provider is served by every plugin binary. It describes what the plugin can
// do and instantiates configured clients.
//
// Compatibility: protocol.ProtocolVersion must be bumped on every change that
// an older host or plugin cannot handle (removed or renumbered fields, changed
// semantics). protocol.ProtoChecksum pins this file so that a change to it
// fails a test until both are looked at.
type ProviderClient interface {
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	// Release frees a configured client. A host calls it when it is done with
	// a client so that a long-lived plugin process does not accumulate them.
	// The host must not have calls in flight for that client: the plugin may
	// close it at once.
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
}

type providerClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderClient(cc grpc.ClientConnInterface) ProviderClient {
	return &providerClient{cc}
}

func (c *providerClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, Provider_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, Provider_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, Provider_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServer is the server API for Provider service.
// All implementations must embed UnimplementedProviderServer
// for forward compatibility.
//
// Provider is served by every plugin binary. It describes what the plugin can
// do and instantiates configured clients.
//
// Compatibility: protocol.ProtocolVersion must be bumped on every change that
// an older host or plugin cannot handle (removed or renumbered fields, changed
// semantics). protocol.ProtoChecksum pins this file so that a change to it
// fails a test until both are looked at.
type ProviderServer interface {
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	// Release frees a configured client. A host calls it when it is done with
	// a client so that a long-lived plugin process does not accumulate them.
	// The host must not have calls in flight for that client: the plugin may
	// close it at once.
	Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	mustEmbedUnimplementedProviderServer()
}

// UnimplementedProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProviderServer struct{}

func (UnimplementedProviderServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedProviderServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedProviderServer) Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedProviderServer) mustEmbedUnimplementedProviderServer() {}
func (UnimplementedProviderServer) testEmbeddedByValue()                  {}

// UnsafeProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderServer will
// result in compilation errors.
type UnsafeProviderServer interface {
	mustEmbedUnimplementedProviderServer()
}

func RegisterProviderServer(s grpc.ServiceRegistrar, srv ProviderServer) {
	// If the following call panics, it indicates UnimplementedProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Provider_ServiceDesc, srv)
}

func _Provider_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provider_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provider_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provider_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Provider_ServiceDesc is the grpc.ServiceDesc for Provider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Provider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "genai.plugin.v1.Provider",
	HandlerType: (*ProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _Provider_Describe_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _Provider_Configure_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _Provider_Release_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "genai/plugin/v1/provider.proto",
}

const (
	ChatCompletion_ChatCompletion_FullMethodName       = "/genai.plugin.v1.ChatCompletion/ChatCompletion"
	ChatCompletion_ChatCompletionStream_FullMethodName = "/genai.plugin.v1.ChatCompletion/ChatCompletionStream"
)

// ChatCompletionClient is the client API for ChatCompletion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChatCompletion mirrors llm.ChatCompletionClient and
// llm.ChatCompletionStreamingClient.
type ChatCompletionClient interface {
	ChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error)
	ChatCompletionStream(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChunk], error)
}

type chatCompletionClient struct {
	cc grpc.ClientConnInterface
}

func NewChatCompletionClient(cc grpc.ClientConnInterface) ChatCompletionClient {
	return &chatCompletionClient{cc}
}

func (c *chatCompletionClient) ChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatCompletionResponse)
	err := c.cc.Invoke(ctx, ChatCompletion_ChatCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatCompletionClient) ChatCompletionStream(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatCompletion_ServiceDesc.Streams[0], ChatCompletion_ChatCompletionStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatCompletionRequest, StreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatCompletion_ChatCompletionStreamClient = grpc.ServerStreamingClient[StreamChunk]

// ChatCompletionServer is the server API for ChatCompletion service.
// All implementations must embed UnimplementedChatCompletionServer
// for forward compatibility.
//
// ChatCompletion mirrors llm.ChatCompletionClient and
// llm.ChatCompletionStreamingClient.
type ChatCompletionServer interface {
	ChatCompletion(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error)
	ChatCompletionStream(*ChatCompletionRequest, grpc.ServerStreamingServer[StreamChunk]) error
	mustEmbedUnimplementedChatCompletionServer()
}

// UnimplementedChatCompletionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatCompletionServer struct{}

func (UnimplementedChatCompletionServer) ChatCompletion(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatCompletion not implemented")
}
func (UnimplementedChatCompletionServer) ChatCompletionStream(*ChatCompletionRequest, grpc.ServerStreamingServer[StreamChunk]) error {
	return status.Error(codes.Unimplemented, "method ChatCompletionStream not implemented")
}
func (UnimplementedChatCompletionServer) mustEmbedUnimplementedChatCompletionServer() {}
func (UnimplementedChatCompletionServer) testEmbeddedByValue()                        {}

// UnsafeChatCompletionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatCompletionServer will
// result in compilation errors.
type UnsafeChatCompletionServer interface {
	mustEmbedUnimplementedChatCompletionServer()
}

func RegisterChatCompletionServer(s grpc.ServiceRegistrar, srv ChatCompletionServer) {
	// If the following call panics, it indicates UnimplementedChatCompletionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatCompletion_ServiceDesc, srv)
}

func _ChatCompletion_ChatCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatCompletionServer).ChatCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatCompletion_ChatCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatCompletionServer).ChatCompletion(ctx, req.(*ChatCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatCompletion_ChatCompletionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatCompletionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatCompletionServer).ChatCompletionStream(m, &grpc.GenericServerStream[ChatCompletionRequest, StreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatCompletion_ChatCompletionStreamServer = grpc.ServerStreamingServer[StreamChunk]

// ChatCompletion_ServiceDesc is the grpc.ServiceDesc for ChatCompletion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatCompletion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "genai.plugin.v1.ChatCompletion",
	HandlerType: (*ChatCompletionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChatCompletion",
			Handler:    _ChatCompletion_ChatCompletion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatCompletionStream",
			Handler:       _ChatCompletion_ChatCompletionStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "genai/plugin/v1/provider.proto",
}

const (
	Embeddings_Embeddings_FullMethodName = "/genai.plugin.v1.Embeddings/Embeddings"
)

// EmbeddingsClient is the client API for Embeddings service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Embeddings mirrors llm.EmbeddingsClient.
type EmbeddingsClient interface {
	Embeddings(ctx context.Context, in *EmbeddingsRequest, opts ...grpc.CallOption) (*EmbeddingsResponse, error)
}

type embeddingsClient struct {
	cc grpc.ClientConnInterface
}

func NewEmbeddingsClient(cc grpc.ClientConnInterface) EmbeddingsClient {
	return &embeddingsClient{cc}
}

func (c *embeddingsClient) Embeddings(ctx context.Context, in *EmbeddingsRequest, opts ...grpc.CallOption) (*EmbeddingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingsResponse)
	err := c.cc.Invoke(ctx, Embeddings_Embeddings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmbeddingsServer is the server API for Embeddings service.
// All implementations must embed UnimplementedEmbeddingsServer
// for forward compatibility.
//
// Embeddings mirrors llm.EmbeddingsClient.
type EmbeddingsServer interface {
	Embeddings(context.Context, *EmbeddingsRequest) (*EmbeddingsResponse, error)
	mustEmbedUnimplementedEmbeddingsServer()
}

// UnimplementedEmbeddingsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmbeddingsServer struct{}

func (UnimplementedEmbeddingsServer) Embeddings(context.Context, *EmbeddingsRequest) (*EmbeddingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Embeddings not implemented")
}
func (UnimplementedEmbeddingsServer) mustEmbedUnimplementedEmbeddingsServer() {}
func (UnimplementedEmbeddingsServer) testEmbeddedByValue()                    {}

// UnsafeEmbeddingsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmbeddingsServer will
// result in compilation errors.
type UnsafeEmbeddingsServer interface {
	mustEmbedUnimplementedEmbeddingsServer()
}

func RegisterEmbeddingsServer(s grpc.ServiceRegistrar, srv EmbeddingsServer) {
	// If the following call panics, it indicates UnimplementedEmbeddingsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Embeddings_ServiceDesc, srv)
}

func _Embeddings_Embeddings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingsServer).Embeddings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Embeddings_Embeddings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingsServer).Embeddings(ctx, req.(*EmbeddingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Embeddings_ServiceDesc is the grpc.ServiceDesc for Embeddings service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Embeddings_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "genai.plugin.v1.Embeddings",
	HandlerType: (*EmbeddingsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Embeddings",
			Handler:    _Embeddings_Embeddings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "genai/plugin/v1/provider.proto",
}
